export const actionTypes = {
  // from db
  GET_DATA_TABLE: "GET_DATA_TABLE",
  SET_DATA_TABLE: "SET_DATA_TABLE",
  // sort
  SET_SORT_TABLE: "SET_SORT_TABLE",
  SET_ORDER_SORT_TABLE: "SET_ORDER_SORT_TABLE",
  SET_COLUMN_TABLE: "SET_COLUMN_TABLE",
  // condition
  SET_WHERE_TABLE: "SET_WHERE_TABLE",
  SET_CONDITION_TABLE: "SET_CONDITION_TABLE",
  SET_INPUT_TABLE: "SET_INPUT_TABLE",
}